version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: tech_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432" # Mapeo para que el backend local la vea