version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: tech_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - backend_net
    # Punto extra: Healthcheck para asegurar que la DB esté lista 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tech_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_NAME: tech_db
      DB_USER: postgres
      DB_PASSWORD: admin
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend_net

networks:
  backend_net:
    driver: bridge